[versions]
agp = "8.9.1"
annotation = "1.9.1"
databindingRuntime = "8.9.1"
fastadapter = "5.7.0"
fastkvJava = "1.2.7"
kotlin = "2.1.20"
ksp = "2.1.20-1.0.31"
aboutlibraries = "11.2.3"
androidndkgif = "1.0.1"
appcompat = "1.7.0"
blockcanary = "0.0.5"
cardview = "1.0.0"
colorPicker = "2.3"
constraintlayout = "2.2.1"
androidxCore = "1.16.0"
dragSelectRecyclerview = "2.4.0"
flexbox = "3.0.0"
glide = "4.16.0"
glideTransformations = "4.3.0"
gpuimage = "2.1.0"
jsoup = "1.18.2"
kotlinxSerializationJson = "1.7.3"
lifecycleRuntimeKtx = "2.8.7"
markwon = "4.6.2"
material = "1.12.0"
materialDialogs = "3.3.0"
okhttp3 = "4.12.0" #okhttp3系列组件版本最高到 4.4.1
parcelableCore = "0.9.0"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
retrofit = "2.11.0"
roaringBitmap = "1.3.0"
room = "2.7.0"
subsamplingScaleImageViewAndroidx = "3.10.0"
swiperefreshlayout = "1.1.0"
vectordrawable = "1.2.0"
viewpager2 = "1.1.0"
webkit = "1.13.0"
workRuntimeKtx = "2.10.0"
ketch = "2.0.5"
zip4j = "2.11.5"
junit-junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
kotlinter = "5.0.1"

[libraries]
aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutlibraries" }
aboutlibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
androidndkgif = { group = "io.github.waynejo", name = "androidndkgif", version.ref = "androidndkgif" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databindingRuntime" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
#androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleRuntimeKtx" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
#androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntimeKtx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
#androidx-work-multiprocess = { group = "androidx.work", name = "work-multiprocess", version.ref = "workRuntimeKtx" }
#androidx-work-rxjava2 = { group = "androidx.work", name = "work-rxjava2", version.ref = "workRuntimeKtx" }
#androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "workRuntimeKtx" }
#aria-core = { group = "com.arialyy.aria", name = "core", version.ref = "aria" }
blockcanary = { group = "io.github.knight-zxw", name = "blockcanary", version.ref = "blockcanary" }
blockcanary-ui = { group = "io.github.knight-zxw", name = "blockcanary-ui", version.ref = "blockcanary" }
#brv = { group = "com.github.liangjingkanji", name = "BRV", version.ref = "brv" }
#brvah = { group = "io.github.cymchad", name = "BaseRecyclerViewAdapterHelper", version.ref = "brvah" }
colorPicker = { group = "com.github.Dhaval2404", name = "ColorPicker", version.ref = "colorPicker" }
drag-select-recyclerview = { group = "com.afollestad", name = "drag-select-recyclerview", version.ref = "dragSelectRecyclerview" }
fastadapter = { module = "com.mikepenz:fastadapter", version.ref = "fastadapter" }
fastadapter-extensions-binding = { module = "com.mikepenz:fastadapter-extensions-binding", version.ref = "fastadapter" }
fastadapter-extensions-diff = { module = "com.mikepenz:fastadapter-extensions-diff", version.ref = "fastadapter" }
fastadapter-extensions-drag = { module = "com.mikepenz:fastadapter-extensions-drag", version.ref = "fastadapter" }
fastadapter-extensions-utils = { module = "com.mikepenz:fastadapter-extensions-utils", version.ref = "fastadapter" }
#fastadapter-extensions-ui = { module = "com.mikepenz:fastadapter-extensions-ui", version.ref = "fastadapter" }
fastadapter-extensions-swipe = { module = "com.mikepenz:fastadapter-extensions-swipe", version.ref = "fastadapter" }
fastadapter-extensions-scroll = { module = "com.mikepenz:fastadapter-extensions-scroll", version.ref = "fastadapter" }
fastadapter-extensions-paged = { module = "com.mikepenz:fastadapter-extensions-paged", version.ref = "fastadapter" }
fastkv-java = { module = "io.github.billywei01:fastkv-java", version.ref = "fastkvJava" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
#flowlayout-lib = { group = "com.hyman", name = "flowlayout-lib", version.ref = "flowlayoutLib" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-annotations = { group = "com.github.bumptech.glide", name = "annotations", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
glide-transformations = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glideTransformations" }
gpuimage = { group = "jp.co.cyberagent.android", name = "gpuimage", version.ref = "gpuimage" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
#kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#loopinglayout = { group = "com.github.beksomega", name = "loopinglayout", version.ref = "loopinglayout" }
markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-dialogs-bottomsheets = { group = "com.afollestad.material-dialogs", name = "bottomsheets", version.ref = "materialDialogs" }
material-dialogs-core = { group = "com.afollestad.material-dialogs", name = "core", version.ref = "materialDialogs" }
material-dialogs-files = { group = "com.afollestad.material-dialogs", name = "files", version.ref = "materialDialogs" }
material-dialogs-input = { group = "com.afollestad.material-dialogs", name = "input", version.ref = "materialDialogs" }
material-dialogs-lifecycle = { group = "com.afollestad.material-dialogs", name = "lifecycle", version.ref = "materialDialogs" }
#mmkv-static = { group = "com.tencent", name = "mmkv-static", version.ref = "mmkvStatic" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp3" }
kotlinx-serialization-parcelable = { module = "com.chrynan.parcelable:parcelable-core", version.ref = "parcelableCore" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
#retrofit-adapter-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofit" }
#retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
#retrofit-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
roaringBitmap = { group = "org.roaringbitmap", name = "RoaringBitmap", version.ref = "roaringBitmap" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
#rxandroid = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid" }
#rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
#rxkotlin = { group = "io.reactivex.rxjava2", name = "rxkotlin", version.ref = "rxkotlin" }
subsampling-scale-image-view-androidx = { group = "com.davemorrissey.labs", name = "subsampling-scale-image-view-androidx", version.ref = "subsamplingScaleImageViewAndroidx" }
zip4j = { group = "net.lingala.zip4j", name = "zip4j", version.ref = "zip4j" }
#io-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
#io-ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
#io-ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
#io-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
#io-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
#io-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
junit = { group = "junit", name = "junit", version.ref = "junit-junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ketch = { group = "com.github.khushpanchal", name = "Ketch", version.ref = "ketch" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }